
version: '3'

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/app
    env_file:
      - ./.env

    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=appointment.settings
      - REDIS_HOST=redis

  redis:
    restart: always
    image: redis:latest 

  #   environment:
  #     - POSTGRES_USER=<your_db_user>
  #     - POSTGRES_PASSWORD=<your_db_password>
  #     - POSTGRES_DB=<your_db_name>

  celery_worker:
    build: .
    restart: always
    command: celery -A appointment worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery_beat:
    build: .
    restart: always
    command: celery -A appointment beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
